language: perl
perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "blead"
sudo: true
matrix:
  include:
    - perl: 5.20
      env: PDL_USE_BADVAL=0 # test with badval disabled
    - perl: 5.20
      env: COVERAGE=1
    - perl: 5.20
      env: COVERAGE=1 PDL_USE_BADVAL=0 # test with badval disabled + coverage
  allow_failures:
    - perl: blead
before_install:
  - export PERL_CPANM_OPT=--dev
  - sudo apt-get update
  - sudo apt-get install gfortran build-essential libx11-dev pgplot5 libplplot-dev libgd2-xpm-dev libhdf4-alt-dev libproj-dev libvpx-dev libxpm-dev proj-bin libcfitsio3-dev libreadline-dev
  - sudo apt-get install libxi-dev libxmu-dev freeglut3-dev libgsl0-dev libnetpbm10-dev # for OpenGL
  - cpanm --quiet --notest ExtUtils::F77 Term::ReadLine::Gnu PGPLOT # do not need to run tests
  - cpanm --quiet --notest version@0.9909
  - cpanm --quiet --dev --notest ExtUtils::MakeMaker # do not need to run tests
  - export PGPLOT_DEV=/NULL
  - perl -pi -e 's|WITH_BADVAL => 1|WITH_BADVAL => 0| if defined $ENV{PDL_USE_BADVAL} && $ENV{PDL_USE_BADVAL} == 0' perldl.conf # disable bad value support
  - eval $(curl https://travis-perl.github.io/init) --auto
after_script:
  - perl -Iblib/lib -MPDL::Config -MData::Dumper -e 'print Dumper \%PDL::Config'
branches:
  except:
    - /^wip\//
    - /^blocked/
