language: perl
perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "blead"
sudo: true
env: PGPLOT_DEV="/NULL"
matrix:
  include:
    - perl: 5.20
      env: COVERAGE=1 PGPLOT_DEV="/NULL"
  allow_failures:
    - perl: blead
before_install:
  - sudo apt-get update
  - sudo apt-get install gfortran build-essential libx11-dev pgplot5 libplplot-dev libgd2-xpm-dev libhdf4-alt-dev libproj-dev libvpx-dev libxpm-dev proj-bin libcfitsio3-dev libreadline-dev
  - sudo apt-get install libxi-dev libxmu-dev freeglut3-dev libgsl0-dev libnetpbm10-dev # for OpenGL
  - cpanm ExtUtils::F77 Term::ReadLine::Gnu PGPLOT
  - eval $(curl https://travis-perl.github.io/init) --auto
branches:
  except:
    - /^wip\//
    - /^blocked/
