language: perl
perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "blead"
sudo: true
matrix:
  include:
    - perl: "5.20"
      env: PDL_WITH_BADVAL=0 # test with badval disabled
    - perl: "5.20"
      env: PDL_WITH_BADVAL=1 PDL_BADVAL_USENAN=0 PDL_BADVAL_PER_PDL=0
    - perl: "5.20"
      env: PDL_WITH_BADVAL=1 PDL_BADVAL_USENAN=0 PDL_BADVAL_PER_PDL=1
    - perl: "5.20"
      env: PDL_WITH_BADVAL=1 PDL_BADVAL_USENAN=1 PDL_BADVAL_PER_PDL=0
    - perl: "5.20"
      env: PDL_WITH_BADVAL=1 PDL_BADVAL_USENAN=1 PDL_BADVAL_PER_PDL=1
    - perl: "5.20"
      env: COVERAGE=1
    - perl: "5.20"
      env: COVERAGE=1 PDL_WITH_BADVAL=0 # test with badval disabled + coverage
  allow_failures:
    - perl: blead
before_install:
  - sudo apt-get update
  - sudo apt-get install gfortran build-essential libx11-dev pgplot5 libplplot-dev libgd2-xpm-dev libhdf4-alt-dev libproj-dev libvpx-dev libxpm-dev proj-bin libcfitsio3-dev libreadline-dev
  - sudo apt-get install libxi-dev libxmu-dev freeglut3-dev libgsl0-dev libnetpbm10-dev # for OpenGL
  - export PGPLOT_DEV=/NULL
  - perl -pi -e 's|WITH_BADVAL => 1|WITH_BADVAL => 0|       if defined $ENV{PDL_WITH_BADVAL}    && $ENV{PDL_WITH_BADVAL}     == 0' perldl.conf # disable bad value support
  - perl -pi -e 's|BADVAL_USENAN => 0|BADVAL_USENAN => 1|   if defined $ENV{PDL_BADVAL_USENAN}  && $ENV{PDL_BADVAL_USENAN}   == 1' perldl.conf # enable BADVAL_USENAN
  - perl -pi -e 's|BADVAL_PER_PDL => 0|BADVAL_PER_PDL => 1| if defined $ENV{PDL_BADVAL_PER_PDL} && $ENV{PDL_BADVAL_PER_PDL}  == 1' perldl.conf # enable BADVAL_PER_PDL
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - ls -lR
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - perl -MExtUtils::ParseXS -e 'print $ExtUtils::ParseXS::VERSION, "\n"'
  - cpanm --quiet --notest ExtUtils::F77 Term::ReadLine::Gnu PGPLOT # do not need tests
  - build-dist
  - cd $BUILD_DIR             # $BUILD_DIR is set by the build-dist command
install:
  - cpan-install --deps       # installs prereqs, including recommends
  - cpan-install --coverage   # installs converage prereqs, if enabled
  - perl -MExtUtils::ParseXS -e 'print $ExtUtils::ParseXS::VERSION, "\n"'
  - make
before_script:
  - coverage-setup
script:
  - prove -b -v $(test-files) # for parallel testing, add --formatter TAP::Formatter::File -j$(test-jobs)
after_script:
  - perl -Iblib/lib -MPDL::Config -MData::Dumper -e 'print Dumper \%PDL::Config'
after_success:
  - coverage-report
branches:
  except:
    - /^wip\//
    - /^blocked/
